-- Update existing hostels with location
update hms_prospects set location = 'Gulistan-e-Johar' where area = 'Gulistan-e-Johar';
update hms_prospects set location = 'Gulshan-e-Iqbal'  where area = 'Gulshan-e-Iqbal';

-- TIER 1 — Clifton + DHA Phase 5 (walking / 5-10 min from 2 Talwar)
insert into hms_prospects (name, owner_name, phone, area, address, maps_url, location, status, notes) values

('6 Star Girls'' Hostel',
 null, '+92 319 2444539',
 'Clifton, Block 5',
 'Bungalow G-22/B, 1 Park Lane, near 3 Talwar, Block 5 Clifton, Karachi 75600',
 'https://www.google.com/maps/place/?q=place_id:ChIJQV02-9w_sz4RpXkoNa-XAwM',
 'Clifton', 'pending',
 'Manager: Ms. Sana (reviews). Literally near 3 Talwar. Tier 1.'),

('Park Lane Girl''s Hostel',
 null, '+92 332 2953573',
 'Clifton, Block 5',
 'F-193, Block 5 Clifton, Karachi 75600',
 'https://www.google.com/maps/place/?q=place_id:ChIJIapkobk9sz4RV7_2jGrBnPk',
 'Clifton', 'pending', 'Tier 1.'),

('Aisha Bawany Girls Hostel Clifton',
 null, null,
 'Clifton, Block 5',
 'G1, FL-19, Block 5 Clifton, Karachi 75600',
 'https://www.google.com/maps/place/?q=place_id:ChIJr3VVYgA9sz4RHYDYYxSyAlU',
 'Clifton', 'pending', 'No phone — walk-in only. Tier 1.'),

('Elite Hostel for Girls Only',
 null, '+92 334 3103533',
 'Clifton, Block 4',
 'Flat 202, Falcon Terrace 1, Block 4 Clifton, Karachi 75600',
 'https://www.google.com/maps/place/?q=place_id:ChIJAcGQEjk9sz4RHSHa4X8e0DA',
 'Clifton', 'pending', 'Tier 1.'),

('Elite Boys Hostel',
 null, '+92 333 3563584',
 'DHA Phase 5, Zamzama Commercial',
 'R28V+M4M, DHA Phase 5 Zamzama Commercial, Defence Housing Authority, Karachi 75600',
 'https://www.google.com/maps/place/?q=place_id:ChIJTTy-YTI9sz4R8Gk75kXBqGM',
 'DHA', 'pending', 'Tier 1.'),

('Bachelors Accommodation',
 null, null,
 'DHA Phase 5',
 'R28W+8WM, D Street, DHA Phase 5, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJM5SGOQA9sz4RM8JDzCE2XpE',
 'DHA', 'pending', 'No phone listed. Tier 1.'),

('Girls Hostel (DHA Phase 5)',
 null, '+92 324 8290276',
 'DHA Phase 5',
 '10th Street Khayaban-e-Mujahid, DHA Phase 5, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJfYb4AWg9sz4RuIa4WMvapbE',
 'DHA', 'pending', 'Tier 1.'),

('Hostels (DHA Phase 6)',
 null, null,
 'DHA Phase 6',
 'R335+P3M, DHA Phase 6, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJj8H_eAA9sz4RtNiNVjsw5OQ',
 'DHA', 'pending', 'No phone listed. Tier 1.'),

-- TIER 2 — Defence View + Saddar (10-20 min drive)
('Professional Stay Boys Hostel',
 null, null,
 'Defence View Phase 2',
 'R3QJ+CFF, Phase 2 Defence View Housing Society, Karachi',
 'https://www.google.com/maps/place/?q=place_id:ChIJm6oGfgA9sz4Rq4EYXgjIuik',
 'Defence View', 'pending',
 '⭐ 4.2★ 115 reviews — very active. Reference: Ahsan Bhai. Visit in-person. Tier 2.'),

('Dua Boys Hostel DHA',
 null, '+92 300 0589834',
 'Defence View Phase 2',
 'Plot BB-9, Phase 2 Defence View Housing Society, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJLdm8QxI8sz4RNi7PTUm-UZE',
 'Defence View', 'pending',
 '⭐ 116 reviews — Rs. 12K/bed mentioned. Tier 2.'),

('Noor Boys Hostel',
 null, '+92 336 3156647',
 'Defence View Phase 3',
 'R3VM+754, Defence View Phase 3, near Iqra University, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJL18KIw48sz4RenJq9j2DP4s',
 'Defence View', 'pending',
 '⭐ 185 reviews — large operation, management criticized. Near Iqra University. Tier 2.'),

('Abiha''s Girls Hostels',
 null, '+92 336 1111109',
 'Defence View Phase 3',
 'Building N-5/N-6, near Defence View Society Road, Phase 3, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJlXt3X7w9sz4RtxoFVVi_PMg',
 'Defence View', 'pending',
 '⭐ 4.5★ — premium girls hostel. Tier 2.'),

('The United Girls Hostels (DHA branch)',
 null, '+92 333 0033666',
 'DHA Phase 2 Extension',
 '20C, 23rd Commercial Street, Phase 2 Ext DHA, Karachi 75500',
 'https://www.google.com/maps/place/?q=place_id:ChIJxc3lcvM9sz4R72gDLyCbaLI',
 'DHA', 'pending',
 'Manager: Sinova Rehmani. Multi-property operator (also in Gulistan-e-Johar). Tier 2.'),

('Karachi Boys Hostel (Saddar)',
 null, null,
 'Saddar',
 '2nd Floor, Panorama Centre 02, behind Hotel Avari, Raja Ghaznafar Ali Khan Road, Saddar, Karachi',
 'https://www.google.com/maps/place/?q=place_id:ChIJlx09yC8_sz4RswSbEK4HoBI',
 'Saddar', 'pending',
 'No phone — behind Hotel Avari. Tier 2.'),

-- TIER 3 — PECHS / Tariq Road (20-30 min drive)
('Hostel Hub - PECHS',
 null, '+92 304 5114466',
 'PECHS Block 2',
 '1st & 2nd Floor, 701/C Tariq Road, Block 2 PECHS, Karachi 75400',
 'https://www.google.com/maps/place/?q=place_id:ChIJRQ92Xj4_sz4RU7WN82x-ucg',
 'Tariq Road', 'pending', 'Tier 3.'),

('Tariq Road Hostel',
 null, '+92 307 5006000',
 'PECHS Block 2',
 'Tariq Road, near Liberty Signal, Block 2 PECHS, Karachi 75400',
 'https://www.google.com/maps/place/?q=place_id:ChIJObOvtik_sz4R--Opo0c5lNA',
 'Tariq Road', 'pending', 'Near Liberty Signal. Tier 3.'),

('Boys Hostel Tariq Road',
 null, '+92 311 1250726',
 'PECHS Block 2',
 'Flat 6, Plot 707/C C-2, 4th Floor, Block 2 PECHS, Karachi 74200',
 'https://www.google.com/maps/place/?q=place_id:ChIJ3Q7uPNQ_sz4R6xFkkks9wGM',
 'Tariq Road', 'pending', 'Tier 3.'),

('Karachi Boys Hostel (Jheel Park)',
 null, '+92 341 0113068',
 'PECHS Block 2',
 'Jheel Park, Flat 202, Plot 841/C-842/C, Tariq Road, near Tariq Center, Block 2 PECHS',
 'https://www.google.com/maps/place/?q=place_id:ChIJ_YckDAA_sz4R_V_zujfHPTI',
 'Tariq Road', 'pending', 'Near Tariq Center. Tier 3.'),

('Karachi Hostel 2',
 null, '+92 370 0834310',
 'PECHS Block 2',
 '1 Tariq Road, Liberty Signal, Block 2 PECHS, Karachi 75400',
 'https://www.google.com/maps/place/?q=place_id:ChIJRUSNxpM_sz4Rs2Zn6DOA29o',
 'Tariq Road', 'pending', 'Tier 3.'),

('New Misali Boys Hostel',
 'Tayyab & Faisal', '+92 339 1234172',
 'PECHS Block 2',
 'Tariq Road, near Rahat Bakery, Block 2 PECHS, Karachi',
 'https://www.google.com/maps/place/?q=place_id:ChIJM4P7KgA_sz4RhNmt-RUbBds',
 'Tariq Road', 'pending',
 '⭐ 4.7★ — premium operation. Owners: Tayyab & Faisal. Near Rahat Bakery. Tier 3.');
