-- Salary advances.
--
-- An advance is a LOAN, not a salary payment. Handing an employee money early
-- moves cash out of the hostel but does not make it a staff cost yet — the cost
-- is still the full month's salary they earn. Booking the advance as an expense
-- AND then paying the salary in full would report 25,000 of staff cost where a
-- 20,000 salary and a 5,000 advance actually occurred.
--
-- So: cash leaves on advance_date, a receivable is created, and the later salary
-- payment is handed over NET. hms_salary_payments.amount stays GROSS (what was
-- earned) and advance_deducted records what was held back.
--
-- Why not reuse hms_salary_payments: it is UNIQUE (employee_id, for_month), and
-- an employee can take two advances in the same month. It also has no partial
-- payment concept (status is only pending/paid, there is no amount_paid), and
-- its rows are regenerated by upsert from employees.monthly_salary — anything
-- written into `amount` is liable to be overwritten.

CREATE TABLE IF NOT EXISTS public.hms_salary_advances (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hostel_id          uuid NOT NULL REFERENCES public.hms_hostels(id)   ON DELETE CASCADE,
  -- RESTRICT, deliberately unlike hms_salary_payments' CASCADE: deleting an
  -- employee currently erases their whole salary history, and letting it also
  -- erase an unrecovered debt would make money owed disappear with a click.
  -- The owner must recover or write off the balance first.
  employee_id        uuid NOT NULL REFERENCES public.hms_employees(id) ON DELETE RESTRICT,

  amount             numeric(10,2) NOT NULL CHECK (amount > 0),
  advance_date       date          NOT NULL DEFAULT CURRENT_DATE,
  payment_method     text,
  receipt_number     text,
  notes              text,

  /** Sum of hms_salary_advance_recoveries for this advance, maintained by trigger. */
  recovered_amount   numeric(10,2) NOT NULL DEFAULT 0 CHECK (recovered_amount >= 0),
  /** Balance the owner gave up on — an employee who left still owing. */
  written_off_amount numeric(10,2) NOT NULL DEFAULT 0 CHECK (written_off_amount >= 0),
  written_off_date   date,
  /** The hms_expenses row booking the write-off, so the two can never be
   *  reconciled by guesswork. See the write-off note at the bottom. */
  written_off_expense_id uuid REFERENCES public.hms_expenses(id) ON DELETE SET NULL,

  -- Can never settle more than was lent.
  CONSTRAINT hms_salary_advances_not_over_settled
    CHECK (recovered_amount + written_off_amount <= amount),

  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Derived, never stored by hand. A status column set by application code drifts
-- from the numbers it claims to describe the first time a write path is missed;
-- generated columns cannot.
ALTER TABLE public.hms_salary_advances
  ADD COLUMN IF NOT EXISTS balance numeric(10,2)
  GENERATED ALWAYS AS (amount - recovered_amount - written_off_amount) STORED;

ALTER TABLE public.hms_salary_advances
  ADD COLUMN IF NOT EXISTS status text
  GENERATED ALWAYS AS (
    CASE
      WHEN written_off_amount > 0 AND amount - recovered_amount - written_off_amount <= 0 THEN 'written_off'
      WHEN amount - recovered_amount - written_off_amount <= 0                            THEN 'recovered'
      WHEN recovered_amount > 0                                                           THEN 'partially_recovered'
      ELSE 'outstanding'
    END
  ) STORED;

-- Drives "what does this employee still owe?" on the staff list and the pay dialog.
CREATE INDEX IF NOT EXISTS hms_salary_advances_employee_idx
  ON public.hms_salary_advances (employee_id, advance_date);
CREATE INDEX IF NOT EXISTS hms_salary_advances_hostel_status_idx
  ON public.hms_salary_advances (hostel_id, status);

-- ── Recoveries ──────────────────────────────────────────────────────────────
-- One row per "this salary payment paid off this much of that advance".
--
-- Needed because a single deduction is ambiguous once two advances are
-- outstanding: without this link you cannot say which debt a deduction settled,
-- and reversing a salary payment has no way to know what to give back.

CREATE TABLE IF NOT EXISTS public.hms_salary_advance_recoveries (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hostel_id          uuid NOT NULL REFERENCES public.hms_hostels(id) ON DELETE CASCADE,
  advance_id         uuid NOT NULL REFERENCES public.hms_salary_advances(id)  ON DELETE CASCADE,
  salary_payment_id  uuid NOT NULL REFERENCES public.hms_salary_payments(id)  ON DELETE CASCADE,
  amount             numeric(10,2) NOT NULL CHECK (amount > 0),
  created_at         timestamptz NOT NULL DEFAULT now(),
  -- One deduction per advance per salary row; a bigger deduction edits this row
  -- rather than stacking a second one.
  UNIQUE (advance_id, salary_payment_id)
);

CREATE INDEX IF NOT EXISTS hms_salary_advance_recoveries_payment_idx
  ON public.hms_salary_advance_recoveries (salary_payment_id);

-- ── recovered_amount is maintained here, not by the app ─────────────────────
-- The running total and the rows that justify it must not be able to disagree.
-- Recomputed from scratch on every change rather than incremented, so a retry
-- or a double-fire cannot drift it.

CREATE OR REPLACE FUNCTION public.hms_sync_advance_recovered()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target uuid := COALESCE(NEW.advance_id, OLD.advance_id);
BEGIN
  UPDATE public.hms_salary_advances a
  SET recovered_amount = COALESCE(
        (SELECT sum(r.amount) FROM public.hms_salary_advance_recoveries r WHERE r.advance_id = target), 0),
      updated_at = now()
  WHERE a.id = target;
  RETURN NULL;
END; $$;

DROP TRIGGER IF EXISTS trg_sync_advance_recovered ON public.hms_salary_advance_recoveries;
CREATE TRIGGER trg_sync_advance_recovered
  AFTER INSERT OR UPDATE OR DELETE ON public.hms_salary_advance_recoveries
  FOR EACH ROW EXECUTE FUNCTION public.hms_sync_advance_recovered();

-- ── Salary payments carry what was held back ────────────────────────────────
-- `amount` remains GROSS. Net handed over = amount - advance_deducted.
-- Additive with a 0 default, so every existing row and every hostel that never
-- gives an advance computes exactly as before.

ALTER TABLE public.hms_salary_payments
  ADD COLUMN IF NOT EXISTS advance_deducted numeric(10,2) NOT NULL DEFAULT 0
  CHECK (advance_deducted >= 0);

COMMENT ON COLUMN public.hms_salary_payments.advance_deducted IS
  'Advance balance held back from this payment. amount stays GROSS (earned); net handed over = amount - advance_deducted.';

-- ── RLS: mirror hms_salary_payments exactly ─────────────────────────────────
-- Owners manage their own hostel; partners read at any tier and write at full.
-- Managers have no staff portal at all, so there is no third case.

ALTER TABLE public.hms_salary_advances            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hms_salary_advance_recoveries  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner manages salary advances" ON public.hms_salary_advances;
CREATE POLICY "Owner manages salary advances" ON public.hms_salary_advances
  FOR ALL
  USING     (EXISTS (SELECT 1 FROM public.hms_hostels h WHERE h.id = hms_salary_advances.hostel_id AND h.owner_id = auth.uid()))
  WITH CHECK(EXISTS (SELECT 1 FROM public.hms_hostels h WHERE h.id = hms_salary_advances.hostel_id AND h.owner_id = auth.uid()));

DROP POLICY IF EXISTS "members_read_salary_advances" ON public.hms_salary_advances;
CREATE POLICY "members_read_salary_advances" ON public.hms_salary_advances
  FOR SELECT USING (hostel_id IN (SELECT hms_partner_hostel_ids()));

DROP POLICY IF EXISTS "members_write_salary_advances" ON public.hms_salary_advances;
CREATE POLICY "members_write_salary_advances" ON public.hms_salary_advances
  FOR ALL
  USING     (hostel_id IN (SELECT hms_partner_full_hostel_ids()))
  WITH CHECK(hostel_id IN (SELECT hms_partner_full_hostel_ids()));

DROP POLICY IF EXISTS "Owner manages advance recoveries" ON public.hms_salary_advance_recoveries;
CREATE POLICY "Owner manages advance recoveries" ON public.hms_salary_advance_recoveries
  FOR ALL
  USING     (EXISTS (SELECT 1 FROM public.hms_hostels h WHERE h.id = hms_salary_advance_recoveries.hostel_id AND h.owner_id = auth.uid()))
  WITH CHECK(EXISTS (SELECT 1 FROM public.hms_hostels h WHERE h.id = hms_salary_advance_recoveries.hostel_id AND h.owner_id = auth.uid()));

DROP POLICY IF EXISTS "members_read_advance_recoveries" ON public.hms_salary_advance_recoveries;
CREATE POLICY "members_read_advance_recoveries" ON public.hms_salary_advance_recoveries
  FOR SELECT USING (hostel_id IN (SELECT hms_partner_hostel_ids()));

DROP POLICY IF EXISTS "members_write_advance_recoveries" ON public.hms_salary_advance_recoveries;
CREATE POLICY "members_write_advance_recoveries" ON public.hms_salary_advance_recoveries
  FOR ALL
  USING     (hostel_id IN (SELECT hms_partner_full_hostel_ids()))
  WITH CHECK(hostel_id IN (SELECT hms_partner_full_hostel_ids()));

COMMENT ON TABLE public.hms_salary_advances IS
  'Money advanced to an employee against future salary. A receivable, not an expense: cash leaves on advance_date, staff cost is still the gross salary. An unrecovered balance only becomes an expense when written off, booked as an hms_expenses row on the write-off date so no already-closed month changes.';
